export const tipoPtBrParaEn: Record<string, string> = {
  grama: 'grass',
  fogo: 'fire',
  água: 'water',
  venenoso: 'poison',
  inseto: 'bug',
  elétrico: 'electric',
  normal: 'normal',
  voador: 'flying',
  gelo: 'ice',
  lutador: 'fighting',
  psíquico: 'psychic',
  pedra: 'rock',
  terra: 'ground',
  fantasma: 'ghost',
  dragão: 'dragon',
  sombrio: 'dark',
  aço: 'steel',
  fada: 'fairy',
};
